// Mock data for pets when database connection fails
export const mockLostPets = [
  {
    id: "1",
    name: "Max",
    type: "Dog",
    breed: "Golden Retriever",
    status: "lost",
    color: "Golden",
    gender: "Male",
    size: "Large",
    imageUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d",
    location: "Central Park, New York",
    reportedDate: "2023-06-15",
    lastSeen: "2023-06-15",
    description: "Friendly dog with a blue collar. Last seen near the lake.",
    coordinates: { lat: 40.7812, lng: -73.9665 },
  },
  {
    id: "2",
    name: "Luna",
    type: "Cat",
    breed: "Siamese",
    status: "lost",
    color: "Cream",
    gender: "Female",
    size: "Medium",
    imageUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba",
    location: "Brooklyn Heights, New York",
    reportedDate: "2023-06-18",
    lastSeen: "2023-06-18",
    description: "Shy cat with blue eyes and a pink collar with bell.",
    coordinates: { lat: 40.6958, lng: -73.9936 },
  },
  {
    id: "3",
    name: "Buddy",
    type: "Dog",
    breed: "Labrador",
    status: "lost",
    color: "Black",
    gender: "Male",
    size: "Large",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb",
    location: "Prospect Park, Brooklyn",
    reportedDate: "2023-06-20",
    lastSeen: "2023-06-20",
    description:
      "Black lab with white patch on chest. Very friendly. Responds to Buddy.",
    coordinates: { lat: 40.6602, lng: -73.969 },
  },
];

export const mockFoundPets = [
  {
    id: "4",
    name: "Unknown",
    type: "Dog",
    breed: "Golden Retriever",
    status: "found",
    color: "Golden",
    gender: "Male",
    size: "Large",
    imageUrl: "https://images.unsplash.com/photo-1561037404-61cd46aa615b",
    location: "East River Park, New York",
    reportedDate: "2023-06-17",
    description: "Found friendly golden dog with blue collar, no tags.",
    coordinates: { lat: 40.7214, lng: -73.9751 },
  },
  {
    id: "5",
    name: "Unknown",
    type: "Cat",
    breed: "Siamese Mix",
    status: "found",
    color: "Cream/Tan",
    gender: "Female",
    size: "Medium",
    imageUrl: "https://images.unsplash.com/photo-1555685812-4b8f594e8e3b",
    location: "Prospect Park, Brooklyn",
    reportedDate: "2023-06-12",
    description: "Found cream-colored cat with blue eyes, very timid.",
    coordinates: { lat: 40.6602, lng: -73.969 },
  },
];
